### ISSUE TITLE
Problèmes contenu d'un Post

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/bordeauxmontaigne-iut#1]
https://bordeauxmontaigne-iut.netlify.app/actualites/2021/11/30/hommage-a-christine-de-rivoyre/

- [x] Assets pas importés
- [x] liens de téléchargement en 404
- [x] partage sociaux marchent pas (url relatives)

**Comment by pabois** [comment]
Même problème sur une "page" : https://bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/

**Comment by pabois** [comment]
Les assets et liens doivent être réparés dans el contenu. 
On ne peut plus sur ce projet refaire l'import depuis le WP.
Je transfère les deux premiers points sur Osuny comme pistes d'amélioration de l'importeur WP
