### ISSUE TITLE
Pages mentionnant organisation

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#103]
Sur les organisations, je serais intéressé pour avoir un bloc "Pages mentionnant..." comme sur le [site exemple](https://example.osuny.org/fr/organisations/rose-primaire/).
J'en ai mentionné deux sur la [page tests](https://www.iut.u-bordeaux-montaigne.fr/tests/) pour voir.

Ça serait pas mal d'avoir aussi les atcus et agendas qui mentionnent l'orga car on a souvent des partenaires sur des évènements. Ça permettrait les mettre plus en avant. Mais il faudrait une autre mise en forme pour que ça soit pas trop "lourd". Peut-être simplement une liste titre + résumé, sans images ni métas ?

**Comment by arnaudlevy** [comment]
@Olivia206 c'est juste un réglage non ?

**Comment by justinpuyo** [comment]
❤️
