### ISSUE TITLE
Couleur hero-essential formations

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#108]
Suite migration du 29/09 :
Couleurs textes et boutons à corriger dans le hero-essential formations.

https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/animation-sociale-et-socioculturelle/

**Comment by alexisben** [comment]
Corrigé dans : https://github.com/osunyorg/theme/pull/624
