### ISSUE TITLE
Balises html dans listes publications

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#109]
Dans les listes des publications, des balises html apparaissent dans publication-meta

![Capture d’écran 2024-10-01 à 10 39 22](https://github.com/user-attachments/assets/e8ee79d2-339e-4c86-85c8-167ad1de6fec)
![Capture d’écran 2024-10-01 à 10 40 06](https://github.com/user-attachments/assets/0b700319-2fbb-405f-9cf0-303537ddde6b)
![Capture d’écran 2024-10-01 à 10 40 39](https://github.com/user-attachments/assets/dd78a8be-89f7-434c-815e-7eba417f7fe1)

**Comment by alexisben** [comment]
Corrigé dans : https://github.com/osunyorg/theme/pull/625
