### ISSUE TITLE
Couleur catégorie page projet

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#111]
Sur les pages projet, la catégorie dans le hero devrait être en blanc.

**Comment by arnaudlevy** [comment]
@justinpuyo tu peux donner l'url stp ?

**Comment by justinpuyo** [comment]
https://www.iut.u-bordeaux-montaigne.fr/projets/2024-n4-retour-a-lenfance/

**Comment by arnaudlevy** [comment]
Mince !
@alexisben pb thème je crois

**Comment by arnaudlevy** [comment]
Merci !

**Comment by arnaudlevy** [comment]
Par contre les liens de partage sont blancs

<img width="547" alt="Capture d’écran 2024-10-22 à 18 10 27" src="https://github.com/user-attachments/assets/1b7178f3-a89b-4f10-ac62-6cba914bdf5a">

**Comment by arnaudlevy** [comment]
@justinpuyo tu veux que je réduise un peu les images ?
Genre 3 cols sur l'index, et image plus petite sur le show ?

**Comment by arnaudlevy** [comment]
Ok c'est moi
