### ISSUE TITLE
Badge "contrôlé par l'état"

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#115]
Oups... j'ai perdu les badges "contrôlés par l'état" sur les pages des formations.

https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/animation-sociale-et-socioculturelle/

**Comment by alexisben** [comment]
Coucou @justinpuyo ! je crois que c'est parce qu'il n'est pas activé sur le diplôme ? https://bordeauxmontaigne.osuny.org/admin/fr/education/diplomas/d2121ee5-6301-4ff8-b622-158c5bec73ba/edit

Est-ce que tu as d'autres formations où c'est bien rempli mais pas affiché ?

**Comment by arnaudlevy** [comment]
Je les active

**Comment by arnaudlevy** [comment]
<img width="1792" alt="Capture d’écran 2024-10-23 à 15 08 03" src="https://github.com/user-attachments/assets/b083576a-0aa5-480f-9f29-8ecbe14e6149">

ok comme ça la couleur ?

parce que bleu sur vert c'est moche

**Comment by justinpuyo** [comment]
> Je les active

Je sais pas ou ça s'active, je n'ai pas vu de case correspondante 🤷‍♂️

**Comment by justinpuyo** [comment]
> ok comme ça la couleur ?
> 
> parce que bleu sur vert c'est moche

Je suis d'accord mais je pense pas qu'on ait le droit de changer la couleur.
Peut-être si on met du blanc entre le macaron central et le liseret ?

**Comment by arnaudlevy** [comment]
> Je sais pas ou ça s'active, je n'ai pas vu de case correspondante 🤷‍♂️

Dans les diplômes !

Je teste la couleur.

**Comment by arnaudlevy** [comment]
bon j'ai pas de solution robuste en CSS, on reste bleu sur vert :/

**Comment by justinpuyo** [comment]
> > Je sais pas ou ça s'active, je n'ai pas vu de case correspondante 🤷‍♂️
> 
> Dans les diplômes !
> 
> Je teste la couleur.

Ah merci, je cherchais dans les formations

**Comment by justinpuyo** [comment]
> bon j'ai pas de solution robuste en CSS, on reste bleu sur vert :/

![Capture d’écran 2024-10-30 à 10 32 00](https://github.com/user-attachments/assets/dbe2d3d7-2c59-41f6-b0b6-d8a23d8d362b)
![Capture d’écran 2024-10-30 à 10 32 14](https://github.com/user-attachments/assets/c0f7478c-b403-4145-9e39-ce6b309d679f)

@arnaudlevy c'est moins moche avec le blanc, non ? Et on reste dans la charte graphique du label

si jamais ça te va, j'ai fait un svg :
![LF_02_BUT_B](https://github.com/user-attachments/assets/badd36b1-49e5-4f17-8ab0-3063e027919b)

**Comment by arnaudlevy** [comment]
<img width="1792" alt="Capture d’écran 2024-10-31 à 12 58 28" src="https://github.com/user-attachments/assets/b8c80a22-47e0-4e49-aafe-739665c4392b">
ça marche !


Si tu veux me faire les autres je les remplacerai aussi
https://www.iut.u-bordeaux-montaigne.fr/assets/images/certifications/diplomas/LP.svg
https://www.iut.u-bordeaux-montaigne.fr/assets/images/certifications/diplomas/grade_M.svg
