### ISSUE TITLE
target site formation

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#116]
Il manque un target="_blank" pour le lien site web d'une formation

https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/

**Comment by arnaudlevy** [comment]
Mince t'as raison

**Comment by Olivia206** [comment]
C'est ajouté merci @justinpuyo !
