### ISSUE TITLE
Pb de grille

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/bordeauxmontaigne-iut#26]
<img width="989" alt="Capture d’écran 2022-06-23 à 16 30 44" src="https://user-images.githubusercontent.com/2088968/175324294-34bed41e-e77b-47a8-87c1-5ed5fcfc5cb9.png">

La gouttière n'est pas respectée, c'est très bizarre, non ? 
J'ai l'impression qu'on n'utilise pas vraiment la grille.

**Comment by arnaudlevy** [comment]
Normalement c'est du 6/6 tout simple

**Comment by sebousan** [comment]
Il y a un espace insécable entre bordeaux et montaigne, par contre manquait bien un padding à droite
