### ISSUE TITLE
Programs : "Rôles" > "Personnes référentes"

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#35]
Dans la section "admission", modifier le titre "Rôles" en "Personnes référentes"

**Comment by arnaudlevy** [comment]
J'ai vu l'issue après, on a mis "Organisation"
https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/#organisation
