### ISSUE TITLE
Bloc organigramme : impossible de ne pas afficher les photos

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#36]
La case "Avec un portrait de chaque personne ? " n'a pas d'effet. Les portraits sont affichés qu'elle soit cochée ou non.

https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/

**Comment by arnaudlevy** [comment]
Oui, ce sera actif dans le nouveau thème AAA !

**Comment by arnaudlevy** [comment]
Ok sur https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/ressources/equipe/
