### ISSUE TITLE
Migration AAA

### ISSUE THREAD

**Issue by alexisben** [osunyorg/bordeauxmontaigne-iut#44]
# Design system

## Typographie

- [x] Enlever l'espace entre un p et un ul [exemple](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/)

# Blocs

## Posts

Les actus dans les pages, en mobile, sont [actuellement](https://www.iut.u-bordeaux-montaigne.fr/formation/scolarite/etre-candidat/) en format liste mais c’est pas le cas en [AAA](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/scolarite/etre-candidat/): est-ce qu’il faut prendre le modèle du site actuel ?

- [x] Trancher le point -> la mise en page est choisie au niveau du bloc, donc c'est le choix de Justin.

https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/

- [x] Titres en bas de page trop gros

## Embed

https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/informations-pratiques/plan-dacces-et-contact/

- [x] Remettre pleine largeur

# Sections

## [Accueil](https://aaa--bordeauxmontaigne-iut.netlify.app)

Parfait !

## [Actualités](https://aaa--bordeauxmontaigne-iut.netlify.app/actualites/)

- [x] Les titres des posts sont trop gros

## [Actualité](https://aaa--bordeauxmontaigne-iut.netlify.app/actualites/2022-12-13-portes-ouvertes-et-salons-2023/)

- [x] L'espace en haut est trop grand (il faut 64px)
- [x] Il manque la table des matières
- [x] Les h2 semblent trop petits

## [Page](https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/)

- [x] L'espace en haut est trop grand (il faut 64px)
- [x] Ajouter le guillemet
- [x] Il manque le texte "Documents spécifiques à la formation continue (Formation Tout au Long de la Vie) :"

## [Équipe](https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/ressources/equipe/)

- [x] Le lead semble trop gros

## [Formations](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/)

- [x] L'espace en haut est trop grand
- [x] L'espace en bas est trop petit (absent)

## [Formation](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/)

- [x] Aligner le bouton télécharger en bas (sur le bas de "durée 3 ans")
- [ ] Traiter les crédits en rollover partout ?
- [x] Dans les [infos administratives](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/#informations-administratives) aligner la droite à droite

## [Diplômes](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/diplomes/)

- [x] Remplacer les faux textes !
- [x] L'équilibre de la page n'est pas beau, les typos sont trop grosses, je ne sais pas pourquoi

## [Diplôme](https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/)

- [x] Idem c'est trop gros

**Comment by arnaudlevy** [comment]
je dirais par défaut en liste, avec une var de config qui le change ? Ou alors s'appuyer sur la config desktop ?

**Comment by alexisben** [comment]
![image](https://user-images.githubusercontent.com/4630530/209162620-1fc59e28-0578-4d4c-ad7f-8ff37300c8ae.png)

ou 

![image](https://user-images.githubusercontent.com/4630530/209162665-9dfba209-6546-47f9-adda-77ec1cbfeddc.png)

**Comment by arnaudlevy** [comment]
https://github.com/noesya/bordeauxmontaigne-iut/issues/44#issuecomment-1362944562
Le menu AAA est très bien, on le laisse tel quel
