### ISSUE TITLE
Pages "Équipe" : couleur et mise en page

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#49]
**Thème AAA**

- [x] La couleur du bandeau est le prune de la home, ça devrait être le bleu.

- [x] Le résumé est en pleine largeur et pas le bloc chapitre : harmoniser l'un ou l'autre.
Je verrai bien les blocs pas en pleine largeur avec en guise de "table des matières" des filtres/tris pour les liste de personnes.

https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/ressources/equipe/equipe-pedagogique/

<img width="1512" alt="Capture d’écran 2023-01-10 à 17 04 07" src="https://user-images.githubusercontent.com/113047726/211601682-bc1bc004-d23d-4426-b4dc-eb80c72adce1.png">

**Comment by arnaudlevy** [comment]
@alexisben il manque de la marge sous la pagination
