### ISSUE TITLE
Bloc liste formations : problème d'affichage

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#50]
Je reposte ça car le problème est toujours là sur AAA
https://aaa--bordeauxmontaigne-iut.netlify.app/tests/

> [justinpuyo] commented [Oct 17, 2022]
> 
> Pour les formations qui ont un parent, le titre ne s'affiche pas
> Aussi, la liste est un peu imposante intégrée dans une page de texte : peut-être proposer plusieurs layouts dont une plus compacte ?
> 
> arnaudlevy commented [Oct 18, 2022]
> 
> Mince, en effet.
> Pb technique + pb graphique (typos trop grosses, il faudrait une taille plus standard)

**Comment by arnaudlevy** [comment]
On a localisé le pb, ça devrait être résolu vite :)

**Comment by arnaudlevy** [comment]
C'est réparé pour le fonctionnel, reste une taille de typos à réparer
