### ISSUE TITLE
La page status 404 correspond à celle par défaut de nginx

### ISSUE THREAD

**Issue by MatteoGauthier** [osunyorg/bordeauxmontaigne-iut#53]
Les urls "Not Found" sur le site https://www.iut.u-bordeaux-montaigne.fr/ correspondent à la page d'erreur par défaut de nginx, une page 404 dédié pourrait être plus adapté pour les utilisateurs.

<img width="508" alt="Capture d’écran 2023-01-26 à 17 59 58" src="https://user-images.githubusercontent.com/32040951/214900576-118d76be-316f-4c74-b99d-d536744907ef.png">

Exemples d'url : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formatdion/diplomes/

**Comment by SebouChu** [comment]
Merci ! On met à jour la config NGINX !

**Comment by arnaudlevy** [comment]
@SebouChu Tu penses pas qu'il serait souhaitable d'avoir des 404 clean dans le thème ?

**Comment by SebouChu** [comment]
@arnaudlevy on a mais le serveur pointe pas dessus

**Comment by arnaudlevy** [comment]
ah ok !
j'ai pas de souvenir d'avoir designé ça, ni Takumi, je regarderai quand ce sera calé :)

**Comment by alexisben** [comment]
C'est le template page par défaut (genre : https://example.osuny.org/zrgzrtgz), j'ai un petit soucis de spacing
