### ISSUE TITLE
Affichage arborescence des formations

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#55]
Pour un meilleure lisibilité, j'aurais besoin de faire apparaitre l'arborescence des formations (parents/enfants) lorsqu'elles sont listées 
- index Offre de formation
- index Dipôlmes
- bloc liste formations

pour avoir quelques chose comme ça par ex :
<img width="1512" alt="Capture d’écran 2023-01-27 à 15 59 11" src="https://user-images.githubusercontent.com/113047726/215118115-f0892707-b0bb-4f45-9f23-9da45c93a814.png">

ET/OU

Avoir la possibilité de ne pas lister les formations qui ont des enfants. Je suis moins convaincu mais j'ai eu la demande plusieurs fois.

**Comment by arnaudlevy** [comment]
C'est à dire enlever Carrières sociales ? Ou enlever Animation sociale et socioculturelle ?

**Comment by justinpuyo** [comment]
> 

Enlever Carrières Sociales.
Soit on fait tout apparaitre avec une arborescence, soit on affiche que les parcours (s'il y en a)

**Comment by arnaudlevy** [comment]
t'as raison c'est un peu dur

**Comment by arnaudlevy** [comment]
https://www.figma.com/file/tQh3oLfNwSt8aoVDuUjQt0/Th%C3%A8me-Osuny?node-id=295%3A1254&t=UnRX9cAfn5743PT1-1 ça irait comme ça ?

**Comment by justinpuyo** [comment]
Oui c'est pas mal

**Comment by arnaudlevy** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/2088968/217251599-9f892a43-2681-4b2c-8a10-43520652c2e8.png">

@alexisben je prépare les data

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/issues/797

**Comment by arnaudlevy** [comment]
@alexisben tu peux bosser avec ça je crois

```
programs:
  - label: >
      Carrières Sociales
    path: >
      /formation/offre-de-formation/carrieres-sociales/
    children: 
      - label: >
          Animation sociale et socioculturelle
        path: >
          /formation/offre-de-formation/animation-sociale-et-socioculturelle/
      - label: >
          Villes et territoires durables
        path: >
          /formation/offre-de-formation/villes-et-territoires-durables/
      - label: >
          Animation sociale et socioculturelle - apprentissage ou formation continue
        path: >
          /formation/offre-de-formation/animation-sociale-et-socioculturelle-app-fc/

  - label: >
      Information - Communication
    path: >
      /formation/offre-de-formation/information-communication/
    children: 
      - label: >
          Métiers du livre et du patrimoine
        path: >
          /formation/offre-de-formation/metiers-du-livre-et-du-patrimoine/
      - label: >
          Communication des organisations
        path: >
          /formation/offre-de-formation/communication-des-organisations/
      - label: >
          Information numérique dans les organisations
        path: >
          /formation/offre-de-formation/information-numerique-dans-les-organisations/
      - label: >
          Publicité
        path: >
          /formation/offre-de-formation/publicite/

```

**Comment by alexisben** [comment]
@arnaudlevy 

Il faut réparer la data en enlevant les chevrons des clés "path" pour : 

```
 - label: >
      Carrières Sociales
    path: /formation/offre-de-formation/carrieres-sociales/
    children: 
      - label: >
          Animation sociale et socioculturelle
        path: /formation/offre-de-formation/animation-sociale-et-socioculturelle/
      - label: >
          Villes et territoires durables
        path: /formation/offre-de-formation/villes-et-territoires-durables/
      - label: >
          Animation sociale et socioculturelle - apprentissage ou formation continue
        path: /formation/offre-de-formation/animation-sociale-et-socioculturelle-app-fc/

```

**Comment by Olivia206** [comment]
@arnaudlevy est-ce que ça te convient comme ça ?

![Image](https://user-images.githubusercontent.com/91660674/219007197-2fb6e6ce-ddae-405a-b796-4a80ffd747e7.png)

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/commit/4b941ee8efedb7b12618f009a0e739e60cb30f7f

**Comment by Olivia206** [comment]
@arnaudlevy pour la version mobile, quel affichage est préférable ?

On a testé avec les icons : 

![Capture d’écran 2023-02-15 à 14 47 04](https://user-images.githubusercontent.com/91660674/219045036-4e62a234-424a-406c-a50a-bd34e80882f4.png)

Avec une marge sur tous les enfants :

![Capture d’écran 2023-02-15 à 14 50 03](https://user-images.githubusercontent.com/91660674/219045443-4216a780-d314-4c30-afd1-f70b68f68e25.png)

Avec la marche sur les enfants des enfants uniquement :

![Capture d’écran 2023-02-15 à 14 47 53](https://user-images.githubusercontent.com/91660674/219045041-9c6c1089-30e0-43df-b17e-817992edc3a2.png)

Et sans rien : 

![Capture d’écran 2023-02-15 à 14 48 14](https://user-images.githubusercontent.com/91660674/219045043-7d9d9b7e-a6d4-40b4-84ac-a59ce2924d7c.png)

**Comment by justinpuyo** [comment]
Bonjour @Olivia206 @arnaudlevy 
Perso je vote pour la version 1. C'est mieux d'avoir la même présentation que sur desktop je pense.
Par contre, quand le titre est sur plusieurs lignes, il faudrait s'aligner sur le début du texte et pas sur l’icône si c'est possible.
Comme ça : 
![219045036-4e62a234-424a-406c-a50a-bd34e80882f4 copie](https://user-images.githubusercontent.com/113047726/219312407-2a107f19-dcc8-4360-9552-185e6d313188.png)

**Comment by Olivia206** [comment]
Bonjour @justinpuyo, Arnaud avait designé hier la version mobile de cette partie, je viens d'ajouter ta remarque, voilà ce que ça donne : 

![Capture d’écran 2023-02-16 à 09 59 35](https://user-images.githubusercontent.com/91660674/219317276-57547c23-c455-4044-9658-db19841d18a0.png)

**Comment by justinpuyo** [comment]
Merci @Olivia206 @arnaudlevy c'est top comme ça !
J'aime bien le changement de graisse pour les enfants. Je verrais bien la même chose pour la version desktop, je trouve ça plus lisible. Non ?

**Comment by justinpuyo** [comment]
@arnaudlevy @alexisben oups ! ça affiche la liste entière des formation sous chaque diplôme : 
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/
et les liens des parents ne sont pas bons !

**Comment by justinpuyo** [comment]
Et est-ce qu'on pourrait avoir le même principe sur les autres pages du coup ?
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/licence-professionnelle/
etc...
Je sais, je suis relou 😬

**Comment by arnaudlevy** [comment]
Attention c'est mal calé en mobile les icônes @Olivia206

**Comment by arnaudlevy** [comment]
@justinpuyo non t'as raison, merci ! J'essaie dans Figma

**Comment by arnaudlevy** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/2088968/219598836-de764daf-6978-411d-a3a7-8b13c4d86331.png">

C'est nickel. @alexisben ou @Olivia206 vous pouvez ?

**Comment by arnaudlevy** [comment]
@justinpuyo sur [l'offre de formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/) c'est mieux de garder l'ordre alphabétique strict

**Comment by Olivia206** [comment]
@arnaudlevy @justinpuyo c'est modifié !

**Comment by justinpuyo** [comment]
> @justinpuyo sur [l'offre de formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/) c'est mieux de garder l'ordre alphabétique strict

@arnaudlevy oui si tu veux (je l'utilise plus cette page 🤭)
avec un outil de recherche et des filtres ça sera bien, parce que sur des listes de 200 ou 300 formations ça sera moins digeste

**Comment by justinpuyo** [comment]
Merci @Olivia206

**Comment by arnaudlevy** [comment]
Idem sur les diplômes je pense, à ce niveau ça fonctionne mieux en ordre alpha

**Comment by arnaudlevy** [comment]
@justinpuyo normalement là c'est presque parfait.

Attention, il faut bien que les parents soient liés à l'école, sinon les enfants disparaissent de la liste.
J'ai corrigé pour Gestion des territoires et développement local.

En revanche il y a un pb sur Animation sociale et socioculturelle - apprentissage ou formation continue.
Son parent est Carrières sociales, mais ce n'est pas le même diplôme, donc il n'apparaît ni d'un côté ni de l'autre.
On peut parler de ce cas pour résoudre proprement ?
A mon avis, le "Bachelor Universitaire de Technologie en apprentissage ou formation continue" n'existe pas séparément, c'est une modalité du "Bachelor Universitaire de Technologie".

**Comment by arnaudlevy** [comment]
Je ferme l'issue, @justinpuyo tu me dis si tu veux qu'on reparle de ce cas particulier ?

**Comment by justinpuyo** [comment]
@arnaudlevy désolé, je suis pas très dispo en ce moment
J'ai toujours un problème sur la page [Diplômes](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/) : sous BUT j'ai la liste complète
cc @Olivia206 @alexisben
