### ISSUE TITLE
Taille de police du résumé

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#57]
Il y a une incohérence dans la taille du résumé des pages en pleine largeur.

Soit elle est la même que sur les pages pas en pleine largeur : 
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/

Soit elle est aussi grosse que le titre de la page : 
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/
https://www.iut.u-bordeaux-montaigne.fr/formation/regimes-dinscriptions/codes-rncp/

**Comment by arnaudlevy** [comment]
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/

celle là est fausse @alexisben @Olivia206 vous savez pourquoi ?

**Comment by alexisben** [comment]
@arnaudlevy il manque le param design.full_width pour cette page, possible de l'ajouter par défaut ?

**Comment by justinpuyo** [comment]
ah, c'est la même taille que le titre du coup @arnaudlevy ?

**Comment by arnaudlevy** [comment]
normalement c'est la même taille que les autres résumés pleine largeur, donc proche du titre, mais le titre en est bold

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/2088968/215136772-ab281027-5232-4e4f-8e34-9fadba238ceb.png">

**Comment by justinpuyo** [comment]
Ah oui, c'est vrai qu'on avait dit qu'il fallait réduire les résumés.

**Comment by arnaudlevy** [comment]
C'est cohérent maintenant !
@alexisben on a réduit un peu ? Je me souviens plus.

**Comment by alexisben** [comment]
![image](https://user-images.githubusercontent.com/4630530/215427567-58cf13bf-3646-4fc1-abc1-32e9536c3e07.png)

Je suis passé de 60px à 54px, ça convient ?

**Comment by justinpuyo** [comment]
@alexisben c'est bon sauf sur la page "[Offre de formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/)" où c'est plus gros

<img width="1288" alt="Capture d’écran 2023-01-30 à 12 01 43 copie" src="https://user-images.githubusercontent.com/113047726/215463271-15636394-9b6e-423b-8efa-b31efccb00d0.png">
