### ISSUE TITLE
Formations : taille des titres

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#61]
Les titres des blocs personnalisés sont plus gros que les autres

ex : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/animation-sociale-et-socioculturelle/

<img width="1028" alt="Capture d’écran 2023-02-02 à 09 37 15" src="https://user-images.githubusercontent.com/113047726/216274306-5bb73efc-8fab-458f-97b3-79ab46cfcd0b.png">

**Comment by alexisben** [comment]
Merci c'est corrigé !
