### ISSUE TITLE
Formations : page publiée à tort

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#62]
La page de la formation est publiée alors que la case "Publiée ?" n'est pas cochée
C'est gênant...
ex : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/communication-editoriale-et-digitale/

**Comment by arnaudlevy** [comment]
tu l'as publiée puis dépubliée ?

**Comment by arnaudlevy** [comment]
je l'ai supprimée à la main du repo git

**Comment by arnaudlevy** [comment]
@SebouChu @pabois on a un pb de publication j'ai l'impression

**Comment by justinpuyo** [comment]
Je l'ai republié car j'ai rempli les infos maintenant.
Il y a effectivement quelques petits soucis avec la publication de nouvelles formations : 

- catégorie d'actu pas crée auto : du coup le bloc actus sur la page affiche la liste des catégories (ex : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/communication-editoriale-et-digitale/)
- j'ai créé une formation "Gestion des territoires et développement local" que j'ai mis parente de "Ingénierie de l’animation territoriale" (qui existait déjà) : la nouvelle ne s'affiche pas sur le site mais sur [Ingénierie de l’animation territoriale](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/ingenierie-de-l-animation-territoriale/), la parente apparait bien dans "Mention", mais le lien pointe vers "Ingénierie de l’animation territoriale"

**Comment by arnaudlevy** [comment]
@pabois la catégorie est pour toi, ton script doit être cassé

**Comment by justinpuyo** [comment]
@arnaudlevy du coup ça aussi c'est bon je crois
