### ISSUE TITLE
Bloc liste actus : mise en avant non prise en compte

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#63]
Cette actu est mise en avant : https://www.iut.u-bordeaux-montaigne.fr/actualites/2022-12-13-portes-ouvertes-et-salons-2023/ 
Elle est bien en premier dans la liste de la page 'Actualités' mais pas dans les blocs liste, par exemple sur cette page : 
https://www.iut.u-bordeaux-montaigne.fr/formation/scolarite/#block-20

**Comment by arnaudlevy** [comment]
@SebouChu @pabois les blocs d'actu ne sont pas mis à jour correctement j'ai l'impression

**Comment by pabois** [comment]
A priori pas un problème de mise à jour de blocs.
Mais les blocs d'actus ignorent les mises en avant (pour le moment)

**Comment by pabois** [comment]
@justinpuyo ça doit être bon ! (mais il faut p-e resauver la page pour ce coup-ci)

**Comment by justinpuyo** [comment]
@pabois super ! Merci
