### ISSUE TITLE
Index diplomes : ne se met pas à jour

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#66]
L'offre ne s'actualise pas correctement sur la page [Diplômes](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/).
J'ai désactivé la formation "Éditeur". Elle n'apparaît plus sur [Offre de formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/) et [Licence pro](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/licence-professionnelle/) mais apparaît toujours sur [Diplômes](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/).

**Comment by arnaudlevy** [comment]
Oui @pabois je crois qu'on va devoir finir notre PR rapidement

**Comment by arnaudlevy** [comment]
@justinpuyo est-ce tout ok maintenant ? Merci :)

**Comment by justinpuyo** [comment]
@arnaudlevy j'ai justement fait des modifs hier et aujourd'hui
donc oui, je confirme que ça fonctionne même si 1 fois j'ai dû refaire publi/depubli
