### ISSUE TITLE
Index diplomes : enfants par ordre alpha

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#67]
Les formations enfants ne sont pas classées par ordre alpha

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/commit/662f90881783d46cd05cfcbbf92d0a8c826150a7

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/commit/860d181b96c89e2f60af97d671b14104652e2bc5
