### ISSUE TITLE
Partage RS non fonctionnel

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#72]
Le partage sur les réseaux sociaux (fb, twitter, linkedin) ne fonctionne pas.
- depuis les boutons de partage intégrés, l'url transmise n'est pas bonne
- lorsqu'on copie/colle une url, les infos pour l'aperçu ne remontent pas (pas de titre, pas d'image, pas d'extrait)

**Comment by alexisben** [comment]
Il semble y avoir un soucis avec le SSL, facebook à l'air de ne pas pouvoir récup les meta : 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/4630530/225028787-106ab494-57fc-4679-a223-f51e69133980.png">

**Comment by arnaudlevy** [comment]
@justinpuyo c'est toujours le même problème : le certificat intermédiaire.

https://status.osuny.org/

**Comment by justinpuyo** [comment]
Hello @arnaudlevy @alexisben 
Le certificat est ok. Du coup ça fonctionne quand on copie/colle une url,
mais en partageant depuis le site l'url envoyé semble incomplète.
Avec facebook j'ai par exemple un message d'erreur "href should represent a valid URL"

**Comment by SebouChu** [comment]
Le fix est en cours de déploiement, désolé !

**Comment by justinpuyo** [comment]
@SebouChu ça m'a l'air bon
