### ISSUE TITLE
Actu "fantome"

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#76]
J'ai une actu "[Rencontre avec Julie Wolkenstein](https://www.iut.u-bordeaux-montaigne.fr/actualites/2023-11-24-rencontre-avec-julie-wolkenstein/)" qui s'affiche en double sur la page [Actualités](https://www.iut.u-bordeaux-montaigne.fr/actualites/), avec deux dates différentes. Pourtant je n'ai créé qu'une seule actu. J'ai essayé de dépublier/publier mais je n'arrive pas à la supprimer.

**Comment by arnaudlevy** [comment]
@SebouChu quand tu te sens une âme de détective, j'ai supprimé le fichier mais pas compris
