### ISSUE TITLE
Bloc Agenda liste : pas d'images

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#77]
Les images des événements ne s'affichent pas en mode liste :(

**Comment by arnaudlevy** [comment]
@alexisben c'est du côté thème, non ?

**Comment by justinpuyo** [comment]
@alexisben 
ex. : [https://www.iut.u-bordeaux-montaigne.fr/tests-agenda/#probleme-images-en-mode-liste](https://www.iut.u-bordeaux-montaigne.fr/tests-agenda/#probleme-images-en-mode-liste)

**Comment by Olivia206** [comment]
Fix dans la PR [#293](https://github.com/noesya/osuny-hugo-theme-aaa/pull/293)
