### ISSUE TITLE
Bloc agenda : problème "encours et à venir"

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#79]
Dans le bloc agenda, la sélection "En cours et à venir" ne semble pas prendre en compte les événements en cours.
ex. : [https://www.iut.u-bordeaux-montaigne.fr/tests-agenda/#probleme-evenements-en-cours](https://www.iut.u-bordeaux-montaigne.fr/tests-agenda/#probleme-evenements-en-cours)

**Comment by arnaudlevy** [comment]
Je check !

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/pull/1639

**Comment by arnaudlevy** [comment]
Réparé !
