### ISSUE TITLE
Plan du site : liste des catégories ?

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#81]
Sur le plan du site je suis tombé sur ça : [Catégories](https://www.iut.u-bordeaux-montaigne.fr/plan-du-site/#categories)
Je suppose que c'est sensé lister les catégories des actu (et événements ?), mais il y a une catégorie que je n'utilise pas sur mon site à la place.

**Comment by arnaudlevy** [comment]
Oups
C'est une catégorie de ce site https://www.sita-vih.fr, créée il y a un an.
Je penche pour une erreur à l'époque, j'ai enlevé à la main.
