### ISSUE TITLE
Actus : crédits image header illisibles

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#82]
Pour les actus il faudrait mettre les crédits de l'image d'en-tête en blanc car c'est illisible sur fond foncé.
ex. : [https://www.iut.u-bordeaux-montaigne.fr/actualites/2024-02-01-candidatures-en-licence-professionnelle-formation-continue-et-apprentissage/](https://www.iut.u-bordeaux-montaigne.fr/actualites/2024-02-01-candidatures-en-licence-professionnelle-formation-continue-et-apprentissage/)

**Comment by Olivia206** [comment]
Fix dans la PR [#290](https://github.com/noesya/osuny-hugo-theme-aaa/pull/290)
