### ISSUE TITLE
Liste à puces plusiquers niveaux

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#83]
Il manque une indentation pour les liste à puces à plusieurs niveaux
ex. : [https://www.iut.u-bordeaux-montaigne.fr/tests/#listes-a-puces-deux-niveaux](https://www.iut.u-bordeaux-montaigne.fr/tests/#listes-a-puces-deux-niveaux)

**Comment by arnaudlevy** [comment]
@Olivia206 tu peux le réparer dans le thème stp ?

**Comment by arnaudlevy** [comment]
@Olivia206 et il y a trop d'espace vertical aussi

**Comment by Olivia206** [comment]
@arnaudlevy trop d'espace vertical ? À quel niveau ? Entre les puces ?
Ou est-ce le line-height qui est trop important ?

**Comment by arnaudlevy** [comment]
@Olivia206 non ça n'est plus le cas, désolé, pb résolu :)

**Comment by Olivia206** [comment]
Fix dans la PR [#291](https://github.com/noesya/osuny-hugo-theme-aaa/pull/291)

**Comment by justinpuyo** [comment]
@Olivia206 ça manque également sur les textes des pages formations
ex. : [https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/mediation-par-le-jeu-et-gestion-de-ludotheques/#contenus-de-la-formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/mediation-par-le-jeu-et-gestion-de-ludotheques/#contenus-de-la-formation)

**Comment by justinpuyo** [comment]
Merci
