### ISSUE TITLE
Outil de recherche non pertinent

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#87]
Dans les résultats de recherche on trouve des actualités, des personnes, la page des publications HAL... mais on ne trouve aucune page du site ou de formation. Or, ce sont ces pages là qui sont les plus importantes !

Par exemple, lorsque je cherche "culture", on devrait me proposer : [Culture](https://www.iut.u-bordeaux-montaigne.fr/vie-etudiante/liut-au-quotidien/culture/) et [Conception de projets et médiation artistique et culturelle](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/conception-de-projets-et-mediation-artistique-et-culturelle-comedia/)

Lorsque je cherche "numérique" : [Information numérique dans les organisations](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/information-numerique-dans-les-organisations/), [Métiers du multimédia et de l'internet](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/), [Services numériques](https://www.iut.u-bordeaux-montaigne.fr/vie-etudiante/services-numeriques/)

**Comment by pabois** [comment]
Effectivement. On va améliorer

**Comment by arnaudlevy** [comment]
@pabois pagefind semble ignorer les h1. C'est fâcheux.

**Comment by arnaudlevy** [comment]
@SebouChu
