### ISSUE TITLE
Fiche personne moche en mobile

### ISSUE THREAD

**Issue by alexisben** [osunyorg/bordeauxmontaigne-iut#89]
https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/marlene-dulaurans/

![image](https://github.com/noesya/bordeauxmontaigne-iut/assets/4630530/fae6f4c7-431d-4e15-9fed-b0c369cc749d)

**Comment by arnaudlevy** [comment]
<img width="470" alt="Capture d’écran 2024-03-06 à 18 23 29" src="https://github.com/noesya/bordeauxmontaigne-iut/assets/2088968/a3d88f75-1a12-4224-adcd-99f3bb8862d2">

J'ai fait dans Figma, c'était pas designé
