### ISSUE TITLE
Mauvais href sur certains liens

### ISSUE THREAD

**Issue by justinpuyo** [osunyorg/bordeauxmontaigne-iut#92]
J'ai un vilain bug dans une liste de liens :
[https://www.iut.u-bordeaux-montaigne.fr/intranet/#services-numeriques](https://www.iut.u-bordeaux-montaigne.fr/intranet/#services-numeriques)
Les quatre derniers liens de la section "Services numériques" ne renvoient pas sur la bonne url.
A la place j'ai l'url https://webmail.u-bordeaux-montaigne.fr/0 avec un chiffre qui change à la fin 

Les url sont pourtant les bonnes dans le back. J'ai regardé le html du bloc mais je n'ai rien vu de bizarre.

**Comment by justinpuyo** [comment]
J'ai déplacé le bloc ici : https://www.iut.u-bordeaux-montaigne.fr/tests/
Parce que j'ai besoin de mes liens qui fonctionnent

**Comment by arnaudlevy** [comment]
Normalement c'est réparé !

**Comment by justinpuyo** [comment]
Merci
